### ISSUE TITLE
displaying video

### ISSUE THREAD

**Issue by KevinHQChen** [pthom/immvision#1]
I've been displaying live video in imgui by creating opengl textures from opencv matrices (source: https://gist.github.com/UnaNancyOwen/acfc71de5b157d2ba22c090b420030e4). After I get a texture, it's pretty easy to display in imgui:
`ImGui::Image( reinterpret_cast<void*>( static_cast<intptr_t>( texture ) ), ImVec2( image.cols, image.rows ) );
`

I was hoping it would be easier to do using immvision. However, ImmVision::Image seems to always display the first frame no matter what I do:
```
// setup
cv::Mat raw;
ImmVision::ImageParams immvisionParams;
immvisionParams = ImmVision::ImageParams();
immvisionParams.ImageDisplaySize = cv::Size(350, 0);
immvisionParams.ZoomKey = "z";

// rendering
if (ImGui::Begin("Raw Image Capture", &guiConf.startImCap, imCapFlags)) {
    raw = imCap->getRawFrame();
    ImmVision::Image("##raw", raw, &immvisionParams);
    ImGui::End();
}
```

Am I missing some parameter or is this not possible with immvision? Thanks in advance!

**Comment by KevinHQChen** [comment]
ah there is a RefreshImage parameter that takes care of it.

would be nice to go into a bit more detail about these parameters in the documentation, but the header file's pretty easy to read as well, thanks!

**Comment by pthom** [comment]
Thanks!
