### ISSUE TITLE
 'imgui.h': No such file or directory

### ISSUE THREAD

**Issue by Roger8** [pthom/immvision#8]
immvision\src\immvision/internal/cv/colormap.h(2,10): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory
Did i build it by the wrong way ?

**Comment by pthom** [comment]
> Did i build it by the wrong way ?

Don't know. How did you build it?

**Comment by Roger8** [comment]
I cloned this repo step by step， and cmake is ok .

**Comment by Roger8** [comment]
May i should put  this  file `imgui.h/cpp`  to the project folder ?

**Comment by pthom** [comment]
Please provide **all the relevant details upfront**. 
Troubleshooting without context is very time-consuming and unproductive for both of us. 

Here's a checklist of the information I need from you:

1. **Operating System**:
   - What OS are you using (e.g., Windows, macOS, Linux) and its version?

2. **OpenCV Installation**:
   - How did you install OpenCV (e.g., via pip, system package manager, or building from source)?
   - What version of OpenCV is installed?

3. **Cloning the Repository**:
   - Did you clone the repository with submodules? (e.g., using `git clone --recurse-submodules` or running `git submodule update --init` afterward).

4. **Build Process**:
   - Which build system are you using (e.g., CMake, Make, or others)?
   - What exact commands did you use to configure and build the project? Please list them.
   - Did you encounter any warnings or errors during the build process? Please share those messages, if any.

I ask that you provide as much detail as possible **in one reply**, as receiving information piece by piece makes it difficult to troubleshoot effectively. With this full context, I can help you much more efficiently and pinpoint the problem faster.

**Comment by Roger8** [comment]
Thanks a lot for your prompt reply. @pthom , My development environment:
1. windows 10 22H2 19045.4894
2. opencv 4.5.4 （i build it from source code) , 
     and i add line `SET(OpenCV_DIR "D:/opencv_build/install/x64/vc14/lib")` to CMakeLists.txt 
3. clone like this 
`git clone https://github.com/pthom/immvision.git
cd immvision
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release`
Its output like this 
```
.Selecting Windows SDK version 10.0.22621.0 to target windows 10.0.19045
Found opencv opencv_DIR=D:/opencv_build/insta11/x64/vc14/lib
immvision openCV DLL PATH=/../bin
- configuring done
- Generating done
Build files have been written to: D:/immvision/build
```
4. build commond `cmake --build . --config Release`
then output like this 
```
immvision\src\immvision/internal/cv/colormap.h(2,10): fatal error C1083: Cannot open include file: 'imgui.h': No such file or directory
```
Now i add files [imgui.h](https://github.com/ocornut/imgui/blob/master/imgui.h) [imgui.cpp](https://github.com/ocornut/imgui/blob/master/imgui.cpp) [imconfig.h](https://github.com/ocornut/imgui/blob/master/imconfig.h)  [imgui_internal.h](https://github.com/ocornut/imgui/blob/master/imgui_internal.h)  [imgui_tables.cpp](https://github.com/ocornut/imgui/blob/master/imgui_tables.cpp) [imgui_widgets.cpp](https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp)  [imstb_rectpack.h](https://github.com/ocornut/imgui/blob/master/imstb_rectpack.h) [imstb_textedit.h](https://github.com/ocornut/imgui/blob/master/imstb_textedit.h) [imstb_truetype.h](https://github.com/ocornut/imgui/blob/master/imstb_truetype.h) to the solution ,  errors 
```
immvision\internal\imgui\imgui_imm.cpp(577,16): error C2065: 'ImGuiCol_DockingPreview': undeclared identifier
immvision\internal\imgui\imgui_imm.cpp(578,16): error C2065: 'ImGuiCol_DockingEmptyBg': undeclared identifier
```
then I commented the two lines ,  it compiled successfully.

**Comment by pthom** [comment]
I cannot reproduce your issue using the exact same steps you described.

Glad you could find a way to solve it eventually
